project:
  type: book 

book:
  title: "Learning from Arguments"
  subtitle: "blono remix"
  author: 
    -  "Daniel Z. Korman (original)"
  chapters:
    - part: Preface
      chapters:
      - index.md
      - preface-students.md
      - preface-instructors.md
    - part: Chapters
      chapters:
      - introduction.md
      - evil.md
      - wager.md
      - personal-identity.md
      - death.md
      - no-freedom.md
      - skepticism.md
      - coercion.md
      - abortion.md
      - eating-animals.md
      - utilitarianism.md
  appendices:
    - logic.md
    - writing.md
    - theses-and-arguments.md
  page-navigation: true

format:
  html:
    tbl-cap-location: bottom
    crossref:
      tbl-title: Matrix
      tbl-prefix: Matrix
      custom:
      - caption-location: top
        key: arg
        kind: float
        reference-prefix: "Argument"
        space-before-numbering: true
      - caption-location: top
        key: exa
        kind: float
        reference-prefix: X
        space-before-numbering: false
    reference-location: section
    theme:
      light: 
        - cosmo
        - custom.scss
      dark: 
        - darkly
        - custom.scss
  # pdf:
  #   documentclass: scrreprt


