project:
  type: book 

book:
  title: "Learning from Arguments"
  subtitle: "blono remix"
  author: 
    -  "Daniel Z. Korman (original)"
  chapters:
    - part: Preface
      chapters:
      - index.md
      - preface-students.md
      - preface-instructors.md
    - part: Chapters
      chapters:
      - introduction.md
      - evil.md
      - wager.md
      - personal-identity.md
      - death.md
      - no-freedom.md
      - skepticism.md
      - coercion.md
      - abortion.md
      - eating-animals.md
      - utilitarianism.md
  appendices:
    - logic.md
    - writing.md
    - theses-and-arguments.md
  page-navigation: true
  downloads: [epub]
  repo-url: https://github.com/dsanson/learning-from-arguments-remix
  repo-actions: [issue, source]

bibliography: [refs.json]
citeproc: true
reference-location: section

filters:
  - label-bullets.lua
  - custom-callout

custom-callout:
  argument:
    icon-symbol: "🥊"
    color: "yellow"
    appearance: "minimal"
  example:
    icon-symbol: "💭"
    color: "purple"
    appearance: "minimal"

tbl-cap-location: bottom
crossref:
  tbl-title: Matrix
  tbl-prefix: Matrix
  def-title: T
  def-prefix: T
  custom:
  - caption-location: top
    key: arg
    kind: float
    reference-prefix: "A"
    space-before-numbering: false
  - caption-location: top
    key: exa
    kind: float
    reference-prefix: "TE" 
    space-before-numbering: false

format:
  html:
    format-links: [epub,typst]
    respect-user-color-scheme: true
    theme:
      light: 
        - cosmo
        - custom.scss
      dark: 
        - darkly
        - custom.scss

  epub:
    css: epub.css

  typst:
    citeproc: true
    bibliography: [refs.json]
    cite-method: citeproc
    pdf-standard: ua-1
